###
GET http://localhost:8080/servlet1

###
GET http://localhost:8080/servlet2

###
GET http://localhost:8080/servlet3?name=John&hobby=reading&hobby=gaming

###
GET http://localhost:8080/servlet4

###
POST http://localhost:8080/servlet5

{
    "name": "John",
    "age": 30,
    "city": "New York"
}