
### fail
POST localhost:8080/user/param
Content-Type: application/json

{
  "username": "modeluser",
  "email": "modeluser@example.com"
}

###
### fail
POST localhost:8080/user/model
Content-Type: application/json

{
  "username": "modeluser",
  "email": "modeluser@example.com"
}

###
POST localhost:8080/user/param?name=JohnDoe&email=johndoe@email.com


### 2. POST /user/model - @ModelAttribute로 보내기
POST http://localhost:8080/user/model?username=modeluser&email=modeluser@example.com


###
POST localhost:8080/user/process
Content-Type: application/json

{
    "username": "modeluser",
    "email": "email@email.json"
}

###
POST localhost:8080/user/process2
Content-Type: application/json

{
  "username": "modeluser",
  "email": "email@email.json"
}