POST http://localhost:8080/order
Content-Type: application/x-www-form-urlencoded

productName=&price=50


###
POST http://localhost:8080/order2
Content-Type: application/x-www-form-urlencoded

productName=&price=50